import React from 'react';
import { BarChart3, TrendingUp, DollarSign, Users, Clock, ShieldCheck, Activity } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const AnalyticsAgent: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-r from-indigo-600 via-blue-600 to-cyan-600 rounded-3xl p-6 md:p-8 text-white shadow-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/20 text-xs font-semibold backdrop-blur-md">
              <BarChart3 className="w-3.5 h-3.5" />
              <span>Real-Time Analytics Agent</span>
            </div>
            <h2 className="text-2xl md:text-3xl font-extrabold mt-2">Revenue, Retention & Engagement Insights</h2>
            <p className="text-indigo-100 text-xs md:text-sm mt-1 max-w-xl">
              Tracks real-time revenue generated by AI agent bookings, patient retention funnels, call handling speed, and doctor schedule utilization.
            </p>
          </div>
          <div className="bg-white/10 backdrop-blur-md p-4 rounded-2xl border border-white/20 text-center">
            <div className="text-3xl font-black">₹3.42L</div>
            <div className="text-xs text-indigo-100 font-medium">Monthly Revenue via AI</div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="border-slate-200">
          <CardContent className="p-4">
            <div className="flex items-center justify-between text-slate-500 text-xs font-semibold">
              <span>Total AI Bookings</span>
              <Users className="w-4 h-4 text-blue-500" />
            </div>
            <p className="text-2xl font-bold text-slate-900 mt-2">482</p>
            <p className="text-[11px] text-emerald-600 font-medium mt-1">↑ +24% vs last month</p>
          </CardContent>
        </Card>

        <Card className="border-slate-200">
          <CardContent className="p-4">
            <div className="flex items-center justify-between text-slate-500 text-xs font-semibold">
              <span>Voice Call Telemetry</span>
              <Clock className="w-4 h-4 text-purple-500" />
            </div>
            <p className="text-2xl font-bold text-slate-900 mt-2">1,240 mins</p>
            <p className="text-[11px] text-emerald-600 font-medium mt-1">1m 45s avg call duration</p>
          </CardContent>
        </Card>

        <Card className="border-slate-200">
          <CardContent className="p-4">
            <div className="flex items-center justify-between text-slate-500 text-xs font-semibold">
              <span>Patient Retention Rate</span>
              <TrendingUp className="w-4 h-4 text-emerald-500" />
            </div>
            <p className="text-2xl font-bold text-slate-900 mt-2">84.2%</p>
            <p className="text-[11px] text-emerald-600 font-medium mt-1">↑ +8.1% post follow-ups</p>
          </CardContent>
        </Card>

        <Card className="border-slate-200">
          <CardContent className="p-4">
            <div className="flex items-center justify-between text-slate-500 text-xs font-semibold">
              <span>Doctor Slot Utilization</span>
              <Activity className="w-4 h-4 text-amber-500" />
            </div>
            <p className="text-2xl font-bold text-slate-900 mt-2">92%</p>
            <p className="text-[11px] text-emerald-600 font-medium mt-1">Peak schedule efficiency</p>
          </CardContent>
        </Card>
      </div>

      <Card className="border-slate-200 shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg font-bold">AI Agent Revenue & Conversion Attribution</CardTitle>
          <CardDescription>Breakdown of bookings and revenue created by each of the 8 Autonomous AI Agents</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {[
              { name: "Inbound Sales Agent", revenue: "₹1,24,500", bookings: "182 Bookings", share: "36%" },
              { name: "Appointment Agent", revenue: "₹94,000", bookings: "142 Bookings", share: "28%" },
              { name: "Outbound Sales Agent", revenue: "₹71,200", bookings: "89 Bookings", share: "21%" },
              { name: "Front Desk Agent", revenue: "₹38,000", bookings: "54 Bookings", share: "11%" },
              { name: "Patient Follow-up Agent", revenue: "₹14,500", bookings: "15 Re-consults", share: "4%" },
            ].map((item, idx) => (
              <div key={idx} className="space-y-1">
                <div className="flex items-center justify-between text-xs font-medium">
                  <span className="text-slate-800 font-bold">{item.name}</span>
                  <span className="text-slate-600">{item.revenue} ({item.bookings})</span>
                </div>
                <div className="w-full h-2.5 bg-slate-100 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-gradient-to-r from-blue-500 to-cyan-500 rounded-full" 
                    style={{ width: item.share }}
                  />
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AnalyticsAgent;
